### ISSUE TITLE
Request to TEST environment using TEST access token fails if production option is set to false

### ISSUE THREAD

**Issue by sunny0183** [duffelhq/duffel-api-dotnet#67]
If i create the client object with TEST access token and **production option set to false** then request to any api endpoint fails with the status code 401 with error 'The access token you have used is not a valid API access token'. See below how the client object is initiated. and the subsequent error message 

`DuffelApiClient client = new DuffelApiClient("duffel_test_*******************************************", production: false);`

```
Requesting offers
Failed with status: 401, request Id: FvK_lY1J3sT3G5cAAPwC
The access token you have used is not a valid API access token
```

But if i create the client object with TEST access token but change the **production option to true** then the code works against any api endpoints on TEST environment and executes all my requests successfully.

`DuffelApiClient client = new DuffelApiClient("duffel_test_*******************************************", production: true);`

So the option for production actually stops the api calls to TEST environment if set to false, which I presume is required for TEST environment calls.

**Comment by jonfinerty** [comment]
Thank you for raising the issue, and sorry for the slow response time. I can reproduce and should shortly have a fix.
